# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fb52d7945fd74fc7dad897e3ce12dce847669af00a73f047fe41416054fdc7949013c9529fe3448f08ab51a513968f77bdcfe83f82f13bc6260801e3b38dc94

test:
  secret_key_base: cb7d2cbfe71ddc7e41a59be410c95941b4cecffdd058fea223ac19af53e155263d1744fe8bc706a910a06a52a41a6b57a14564b1fb306b0c153431b5e6d016c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
